routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/mail', 'MailController@mail')->name('mail');

Route::resource('article', 'ArticleController');
Route::resource('ucenik', 'UcenikController');
Route::resource('skola', 'SkolaController');
Route::resource('profesor', 'ProfesorController');
Route::resource('biblioteka', 'BibliotekaController');
Route::resource('knjiga', 'KnjigaController');
Route::resource('dogadjaj', 'DogadjajController');




Route::get('test', function () {
    return view('articles.test');
});

Route::resource('skola.napomena', 'NapomenaController', [
    'only' => ['store', 'create', 'destroy']
]);

Route::get('skola/{skola}/napomena/edit', 'NapomenaController@edit')->name('skola.napomena.edit');

resources/views/skole/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Novo ime skole</div>
                    @foreach($errors->all() as $error)
                        <p style="color:red;">{{ $error }}</p>
                    @endforeach
                    <div class="panel-body">
                        {{ Form::open(['route' => 'skola.store', 'method' => 'POST']) }}
                        <div class="form-group required {{ $errors->first('ime', 'has-error') }}">
                            {{ Form::label('naziv_skole', 'Ime skole', ['class' => 'control-label']) }}
                            {{ Form::text('naziv_skole', '', ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('prezime', 'has-error') }}">
                            {{ Form::label('ulica', 'Ulica skole', ['class' => 'control-label']) }}
                            {{ Form::text('ulica', '', ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('godiste', 'has-error') }}">
                            {{ Form::label('broj', 'Broj skole', ['class' => 'control-label']) }}
                            {{ Form::text('broj', '', ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::submit('Sacuvaj', ['class' => 'btn btn-primary']) }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/skole/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Nova skola</div>
                    <div class="panel-body">

                        {{ Form::open(['route' => ['skola.update', $skola->id], 'method' => 'PUT']) }}
                        <div class="form-group required {{ $errors->first('title', 'has-error') }}">
                            {{ Form::label('naziv_skole', 'Ime skole', ['class' => 'control-label']) }}
                            {{ Form::text('naziv_skole', $skola->naziv_skole, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('text', 'has-error') }}">
                            {{ Form::label('ulica', 'Ulica', ['class' => 'control-label']) }}
                            {{ Form::text('ulica', $skola->ulica, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('text', 'has-error') }}">
                            {{ Form::label('broj', 'Broj', ['class' => 'control-label']) }}
                            {{ Form::number('broj', $skola->broj, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('text', 'has-error') }}">
                            {{ Form::label('napomena', 'Napomena', ['class' => 'control-label']) }}
                            {{ Form::textarea('napomena', $skola->napomena, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::submit('Sacuvaj', ['class' => 'btn btn-primary']) }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/skole/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Lista skola</div>
                    @if(count($skole))
                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                <th>Id</th>
                                <th>Naziv skole</th>
                                <th>Ulica</th>
                                <th>Broj</th>
                                <th>Izmeni</th>
                                <th>Obrisi</th>
                                </thead>
                                <tbody>
                                @foreach($skole as $skola)
                                    <tr>
                                        <td>{{ $skola->id }}</td>
                                        <td>{{ $skola->naziv_skole }}</td>
                                        <td>{{ $skola->ulica }}</td>
                                        <td>{{ $skola->broj }}</td>
                                        <td><a href="{{ route('skola.edit', [$skola->id]) }}" class="btn btn-default">Izmeni</a></td>
                                        <td>
                                            {{ Form::open(['route' => ['skola.destroy', $skola->id], 'method' => 'DELETE']) }}
                                            {{ Form::submit('Obrisi', ['class' => 'btn btn-danger']) }}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div>Nema Skole</div>
                    @endif
                </div>
            </div>
        </div>
        <div class="row">
            @foreach(['Dusan', 'Mladen', 'Bob'] as $ime)
                <p>{{ $ime }}</p>
            @endforeach
        </div>
    </div>
@endsection

resources/views/skole/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div>
                    <p>Id skole:</p>
                    <p>{{ $skola->id }}</p>
                </div>
                <div>
                    <p>Naziv skole:</p>
                    <p>{{ $skola->naziv_skole }}</p>
                </div>
                <div>
                    <p>Ulica:</p>
                    <p>{{ $skola->ulica }}</p>
                </div>
                <div>
                    <p>Broj:</p>
                    <p>{{ $skola->broj }}</p>
                </div>
                <div>
                    <a href="{{ route('skola.napomena.create', ['skola' => $skola->id]) }}" class="btn btn-primary">Dodaj napomene</a>
                </div>
                <div>
                    <p>Napomene:</p>
                    @if(count($skola->napomene) > 0)
                        @foreach($skola->napomene as $napomena)
                            <div style="border: 1px solid #cccccc;">
                                <p>{{ $napomena->naziv }}</p>
                                <p>{{ $napomena->tekst }}</p>
                            </div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection