routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/mail', 'MailController@mail')->name('mail');

Route::resource('article', 'ArticleController');
Route::resource('ucenik', 'UcenikController');
Route::resource('skola', 'SkolaController');
Route::resource('profesor', 'ProfesorController');
Route::resource('biblioteka', 'BibliotekaController');
Route::resource('knjiga', 'KnjigaController');
Route::resource('dogadjaj', 'DogadjajController');




Route::get('test', function () {
    return view('articles.test');
});

Route::resource('skola.napomena', 'NapomenaController', [
    'only' => ['store', 'create', 'destroy']
]);

Route::get('skola/{skola}/napomena/edit', 'NapomenaController@edit')->name('skola.napomena.edit');

resources/views/biblioteke/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Nova biblioteka</div>

                    @foreach($errors->all() as $error)
                        <p style="color:red;">{{ $error }}</p>
                    @endforeach
                    <div class="panel-body">
                        {{ Form::open(['route' => 'biblioteka.store', 'method' => 'POST']) }}
                        <div class="form-group required {{ $errors->first('naziv', 'has-error') }}">
                            {{ Form::label('naziv', 'Naziv biblioteke', ['class' => 'control-label']) }}
                            {{ Form::text('naziv', '', ['class' => 'form-control']) }}
                        </div>

                        <div class="form-group required {{ $errors->first('ulica', 'has-error') }}">
                            {{ Form::label('ulica', 'Ulica', ['class' => 'control-label']) }}
                            {{ Form::text('ulica', '', ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::submit('Sacuvaj', ['class' => 'btn btn-primary']) }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/biblioteke/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Nova biblioteka</div>
                    <div class="panel-body">

                        {{ Form::open(['route' => ['biblioteka.update', $biblioteka->id], 'method' => 'PUT']) }}
                        <div class="form-group required {{ $errors->first('title', 'has-error') }}">
                            {{ Form::label('naziv', 'Naziv biblioteke', ['class' => 'control-label']) }}
                            {{ Form::text('naziv', $biblioteka->naziv, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('text', 'has-error') }}">
                            {{ Form::label('ulica', 'Ulica', ['class' => 'control-label']) }}
                            {{ Form::text('ulica', $biblioteka->ulica, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::submit('Sacuvaj', ['class' => 'btn btn-primary']) }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/biblioteke/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Lista biblioteka</div>
                    @if(count($biblioteke))
                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                <th>Id</th>
                                <th>Naziv</th>
                                <th>Ulica</th>
                                <th>Izmeni</th>
                                <th>Obrisi</th>
                                </thead>
                                <tbody>
                                @foreach($biblioteke as $biblioteka)
                                    <tr>
                                        <td>{{ $biblioteka->id }}</td>
                                        <td>{{ $biblioteka->naziv }}</td>
                                        <td>{{ $biblioteka->ulica }}</td>
                                        <td>{{ isset($biblioteka->knjiga->naziv) ? $biblioteka->knjiga->naziv : '-' }}</td>
                                        <td><a href="{{ route('biblioteka.edit', [$biblioteka->id]) }}" class="btn btn-default">Izmeni</a></td>
                                        <td>
                                            {{ Form::open(['route' => ['biblioteka.destroy', $biblioteka->id], 'method' => 'DELETE']) }}
                                            {{ Form::submit('Obrisi', ['class' => 'btn btn-danger']) }}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div>Nema Biblioteke</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/biblioteke/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div>
                    <p>Id biblioteke:</p>
                    <p>{{ $biblioteka->id }}</p>
                </div>
                <div>
                    <p>Naziv biblioteke:</p>
                    <p>{{ $biblioteka->naziv }}</p>
                </div>
                <div>
                    <p>Ulica:</p>
                    <p>{{ $biblioteka->ulica }}</p>
                </div>
                <div>
                    <a href="{{ route('biblioteka.create', ['biblioteka' => $biblioteka->id]) }}" class="btn btn-primary">Dodaj knjigu</a>
                </div>
                <div>
                    <p>Knjiga:</p>
                    @if(count($biblioteka->knjige) > 0)
                        @foreach($biblioteka->knjige as $knjiga)
                            <div style="border: 1px solid #cccccc;">
                                <p>{{ $knjiga->naziv }}</p>
                                <p>{{ $knjiga->autor }}</p>
                                <p>{{ $knjiga->broj_strana }}</p>
                            </div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection