routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/mail', 'MailController@mail')->name('mail');

Route::resource('article', 'ArticleController');
Route::resource('ucenik', 'UcenikController');
Route::resource('skola', 'SkolaController');
Route::resource('profesor', 'ProfesorController');
Route::resource('biblioteka', 'BibliotekaController');
Route::resource('knjiga', 'KnjigaController');
Route::resource('dogadjaj', 'DogadjajController');




Route::get('test', function () {
    return view('articles.test');
});

Route::resource('skola.napomena', 'NapomenaController', [
    'only' => ['store', 'create', 'destroy']
]);

Route::get('skola/{skola}/napomena/edit', 'NapomenaController@edit')->name('skola.napomena.edit');

resources/views/knjige/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Nova knjiga</div>

                    @foreach($errors->all() as $error)
                        <p style="color:red;">{{ $error }}</p>
                    @endforeach
                    <div class="panel-body">
                        {{ Form::open(['route' => 'knjiga.store', 'method' => 'POST']) }}
                        <div class="form-group required {{ $errors->first('ime', 'has-error') }}">
                            {{ Form::label('naziv', 'Naziv knjige', ['class' => 'control-label']) }}
                            {{ Form::text('naziv', '', ['class' => 'form-control']) }}
                        </div>

                        <div class="form-group required {{ $errors->first('autor', 'has-error') }}">
                            {{ Form::label('autor', 'Autor knjige', ['class' => 'control-label']) }}
                            {{ Form::text('autor', '', ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('godiste', 'has-error') }}">
                            {{ Form::label('broj_strana', 'Broj strana', ['class' => 'control-label']) }}
                            {{ Form::text('broj_strana', '', ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('biblioteka', 'has-error') }}">
                            {{ Form::label('biblioteka', 'Biblioteka', ['class' => 'control-label']) }}
                            {{ Form::select('biblioteka', $biblioteke, null, ['class' => 'form-control', 'placeholder' => 'Izaberite...']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::submit('Sacuvaj', ['class' => 'btn btn-primary']) }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/knjige/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Nova knjiga</div>
                    <div class="panel-body">
                        {{ Form::open(['route' => ['knjiga.update', $knjiga->id], 'method' => 'PUT']) }}
                        <div class="form-group required {{ $errors->first('title', 'has-error') }}">
                            {{ Form::label('naziv', 'Naziv knjige', ['class' => 'control-label']) }}
                            {{ Form::text('naziv', $knjiga->naziv, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('text', 'has-error') }}">
                            {{ Form::label('autor', 'Autor knjige', ['class' => 'control-label']) }}
                            {{ Form::text('autor', $knjiga->autor, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('text', 'has-error') }}">
                            {{ Form::label('broj_strana', 'Broj strana', ['class' => 'control-label']) }}
                            {{ Form::number('broj_strana', $knjiga->broj_strana, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group required {{ $errors->first('skola', 'has-error') }}">
                            {{ Form::label('biblioteka', 'Biblioteka', ['class' => 'control-label']) }}
                            {{ Form::select('biblioteka', $biblioteke, isset($knjiga->biblioteka_id) ? $knjiga->biblioteka_id : null, ['class' => 'form-control', 'placeholder' => 'Izaberite...']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::submit('Sacuvaj', ['class' => 'btn btn-primary']) }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/knjige/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Lista knjiga</div>
                    @if(count($knjige))
                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                <th>Id</th>
                                <th>Naziv</th>
                                <th>Autor</th>
                                <th>Broj strana</th>
                                <th>Biblioteka</th>
                                <th>Izmeni</th>
                                <th>Obrisi</th>
                                </thead>
                                <tbody>
                                @foreach($knjige as $knjiga)
                                    <tr>
                                        <td>{{ $knjiga->id }}</td>
                                        <td>{{ $knjiga->naziv }}</td>
                                        <td>{{ $knjiga->autor }}</td>
                                        <td>{{ $knjiga->broj_strana }}</td>
                                        <td>{{ isset($knjiga->biblioteka->naziv) ? $knjiga->biblioteka->naziv : '-' }}</td>
                                        <td><a href="{{ route('knjiga.edit', [$knjiga->id]) }}" class="btn btn-default">Izmeni</a></td>
                                        <td>
                                            {{ Form::open(['route' => ['knjiga.destroy', $knjiga->id], 'method' => 'DELETE']) }}
                                            {{ Form::submit('Obrisi', ['class' => 'btn btn-danger']) }}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div>Nema Knjige</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/knjige/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div>
                    <p>Id knjige:</p>
                    <p>{{ $knjiga->id }}</p>
                </div>
                <div>
                    <p>Naziv knjige:</p>
                    <p>{{ $knjiga->naziv }}</p>
                </div>
                <div>
                    <p>Autor knjige:</p>
                    <p>{{ $knjiga->autor }}</p>
                </div>
                <div>
                    <p>Broj strana:</p>
                    <p>{{ $knjiga->broj_strana }}</p>
                </div>
                <div>
                    <p>Biblioteka:</p>
                    <p>{{ $knjiga->biblioteka->naziv }}</p>
                </div>

            </div>
        </div>
    </div>
@endsection