routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/mail', 'MailController@mail')->name('mail');

Route::resource('article', 'ArticleController');
Route::resource('ucenik', 'UcenikController');
Route::resource('skola', 'SkolaController');
Route::resource('profesor', 'ProfesorController');
Route::resource('biblioteka', 'BibliotekaController');
Route::resource('knjiga', 'KnjigaController');
Route::resource('dogadjaj', 'DogadjajController');




Route::get('test', function () {
    return view('articles.test');
});

Route::resource('skola.napomena', 'NapomenaController', [
    'only' => ['store', 'create', 'destroy']
]);

Route::get('skola/{skola}/napomena/edit', 'NapomenaController@edit')->name('skola.napomena.edit');

app/Models/Article.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $table = 'articles';

    protected $fillable = [
        'title',
        'text'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::with('user')->get();

        return view('articles.index', [
            'articles' => $articles
        ]);
    }   

    public function create()
    {
        return view('articles.create');
    }

    public function store(Request $request)
    {
        $user = auth()->user();

        $article = new Article();
        $article->title = $request->title;
        $article->text = $request->text;
        $article->user()->associate($user);
        $article->save();

        return redirect()->route('article.index');
    }

    public function show($id)
    {
        $article = Article::where('id', '=', $id)->first();

        return view('articles.show', [
            'article' => $article
        ]);
    }

    public function edit(Request $request, $id)
    {
        $article = Article::where('id', '=', $id)->first();

        return view('articles.edit', [
            'article' => $article
        ]);
    }

    public function update(Request $request, $id)
    {
        $article = Article::where('id', '=', $id)->first();
        $article->title = $request->title;
        $article->text = $request->text;

        $article->save();

        return redirect()->route('article.show', ['id' => $id]);
    }

    public function destroy($id)
    {
        // ISTO
        $article = Article::where('id', '=', $id)->first();

        $article->delete();

//        Article::destroy($id);

        return redirect()->route('article.index');
    }}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Novi artikl</div>

                    <div class="panel-body">
                        {{ Form::open(['route' => 'article.store', 'method' => 'POST']) }}
                        @include('articles.form')
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Novi artikl</div>

                    <div class="panel-body">
                        {{ Form::open(['route' => ['article.update', $article->id], 'method' => 'PUT']) }}
                        @include('articles.form')
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/form.blade.php
<div class="form-group required {{ $errors->first('title', 'has-error') }}">
    {{ Form::label('title', 'Naziv artikla', ['class' => 'control-label']) }}
    {{ Form::text('title', (isset($article)) ? $article->title : '', ['class' => 'form-control']) }}
</div>
<div class="form-group required {{ $errors->first('text', 'has-error') }}">
    {{ Form::label('text', 'Naziv artikla', ['class' => 'control-label']) }}
    {{ Form::textarea('text', (isset($article)) ? $article->text : '', ['class' => 'form-control']) }}
</div>
<div class="form-group">
    {{ Form::submit('Sacuvaj', ['class' => 'btn btn-primary']) }}
</div>

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Lista clanaka</div>
                    @if(count($articles))
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <th>Id</th>
                                <th>Naziv</th>
                                <th>Tekst</th>
                                <th>Edit</th>
                                <th>Obrisi</th>
                            </thead>
                            <tbody>
                            <a href="#">Mladen link</a>
                                @foreach($articles as $article)
                                <tr>
                                    <td>{{ $article->id }}</td>
                                    <td><a href="{{ route('article.show', [$article->id]) }}">{{ $article->title }}</a></td>
                                    <td>{{ $article->text }}</td>
                                    <td><a href="{{ route('article.edit', [$article->id]) }}" class="btn btn-default">Izmeni</a></td>
                                    <td>
                                        {{ Form::open(['route' => ['article.destroy', $article->id], 'method' => 'DELETE']) }}
                                        {{ Form::submit('Obrisi', ['class' => 'btn btn-danger']) }}
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    @else
                        <div>Nema clanaka</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div>
                    <p>Naziv artikla:</p>
                    <p>{{ $article->title }}</p>
                </div>
                <div>
                    <p>Tekst artikla:</p>
                    <p>{{ $article->text }}</p>
                </div>
            </div>
        </div>
        <div>Obrisi clanak</div>
        <div>
            {{ Form::open(['route' => ['article.destroy', $article->id], 'method' => 'DELETE']) }}
            {{ Form::submit('Obrisi', ['class' => 'btn btn-danger']) }}
            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/articles/test.blade.php
<?php
    $var = 5;
?>

@if(isset($var))
    {{ dd('Da') }}
@else
    {{ dd('Ne') }}
@endif